insertsort: Actors.o Main.o
	    g++ Actors.o Main.o -o insertsort

Actors.o: Actors.cpp Actors.h moviepointer.h
	  g++ -c Actors.cpp

Main.o: Main.cpp moviepointer.h InsertionSort.h
	g++ -c Main.cpp
